import type { Metadata } from 'next';

import { QueryProvider } from 'provider/queryProvider';
import { RecoilProvider } from 'provider/recoilProvider';
import { ReactNode } from 'react';

import './globals.css';

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang='ko'>
      <QueryProvider>
        <RecoilProvider>
          <body>{children}</body>
        </RecoilProvider>
      </QueryProvider>
    </html>
  );
}
