export const enum Genres {
  ACTION = 'Action',
  ADVENTURE = 'Adventure',
  ANIMATION = 'Animation',
  COMEDY = 'Comedy',
  CRIME = 'Crime',
  DRAMA = 'Drama',
  FANTASY = 'Fantasy',
  HORROR = 'Horror',
  MYSTERY = 'Mystery',
  ROMANCE = 'Romance',
  THRILLER = 'Thriller',
  DOCUMENTARY = 'Documentary',
  FAMILY = 'Family',
  MUSIC = 'Music',
  MUSICAL = 'Musical',
  SPORT = 'Sport',
  WAR = 'War',
}
